sources:
  - name: Spotify
    handler:
      jsonSchema:
        baseSchema: ./json-schemas/baseSchema.json
        baseUrl: https://api.spotify.com/v1/
        operations:
          - type: Query
            field: album
            description: 'Get an Album: Get Spotify catalog information for a single album.'
            path: /albums/{args.id}
            requestSchema: ./json-schemas/album.request.json
            responseTypeName: AlbumObject
          - type: Query
            field: albums
            description: >-
              Get Multiple Albums: Get Spotify catalog information for multiple
              albums identified by their Spotify IDs.
            path: /albums
            requestSchema: ./json-schemas/albums.request.json
            responseSchema: ./json-schemas/albums.response.json
          - type: Query
            field: albumTracks
            description: 'Get an Album: Get Spotify catalog information for a single album.'
            path: /albums/{args.id}/tracks
            requestSchema: ./json-schemas/albumTracks.request.json
            responseSchema: ./json-schemas/albumTracks.response.json
          - type: Query
            field: artist
            description: >-
              Get an Artist: Get Spotify catalog information for a single artist
              identified by their unique Spotify ID.
            path: /artists/{args.id}
            requestSchema: ./json-schemas/artist.request.json
            responseTypeName: ArtistObject
          - type: Query
            field: artistAlbums
            description: >-
              Get an Artist's Albums: Get Spotify catalog information about an
              artist’s albums.
            path: /artists/{args.id}/albums
            requestSchema: ./json-schemas/artistAlbums.request.json
            responseSchema: ./json-schemas/artistAlbums.response.json
          - type: Query
            field: artistRelatedArtists
            description: >-
              Get an Artist's Related Artists: Get Spotify catalog information
              about artists similar to a given artist. Similarity is based on
              analysis of the Spotify community’s listening history.
            path: /artists/{args.id}/related-artists
            responseSchema: ./json-schemas/artistRelatedArtists.response.json
          - type: Query
            field: artists
            description: >-
              Get Multiple Artists: Get Spotify catalog information for several
              artists based on their Spotify IDs.
            path: /artists
            requestSchema: ./json-schemas/artists.request.json
            responseSchema: ./json-schemas/artists.response.json
          - type: Query
            field: artistTopTracks
            description: >-
              Get an Artist's Top Tracks: Get Spotify catalog information about
              an artist’s top tracks by country.
            path: /artists/{args.id}/top-tracks
            requestSchema: ./json-schemas/artistTopTracks.request.json
            responseSchema: ./json-schemas/artistTopTracks.response.json
          - type: Query
            field: browseCategories
            description: >-
              Get All Categories: Get a list of categories used to tag items in
              Spotify (on, for example, the Spotify player’s “Browse” tab).
            path: /browse/categories
            requestSchema: ./json-schemas/browseCategories.request.json
            responseSchema: ./json-schemas/browseCategories.response.json
          - type: Query
            field: browseCategory
            description: >-
              Get a Category: Get a single category used to tag items in Spotify
              (on, for example, the Spotify player’s “Browse” tab).
            path: /browse/categories/{args.category_id}
            requestSchema: ./json-schemas/browseCategory.request.json
            responseTypeName: CategoryObject
          - type: Query
            field: browseCategoryPlaylists
            description: >-
              Get a Category's Playlists: Get a list of Spotify playlists tagged
              with a particular category.
            path: /browse/categories/{args.category_id}/playlists
            requestSchema: ./json-schemas/browseCategoryPlaylists.request.json
            responseSchema: ./json-schemas/browseCategoryPlaylists.response.json
          - type: Query
            field: browseFeaturedPlaylists
            description: >-
              Get All New Releases: Get a list of new album releases featured in
              Spotify (shown, for example, on a Spotify player’s “Browse” tab).
            path: /browse/featured-playlists
            requestSchema: ./json-schemas/browseFeaturedPlaylists.request.json
            responseSchema: ./json-schemas/browseFeaturedPlaylists.response.json
          - type: Query
            field: browseNewReleases
            description: >-
              Get All New Releases: Get a list of new album releases featured in
              Spotify (shown, for example, on a Spotify player’s “Browse” tab).
            path: /browse/new-releases
            requestSchema: ./json-schemas/browseNewReleases.request.json
            responseSchema: ./json-schemas/browseNewReleases.response.json
          - type: Query
            field: playerRecentlyPlayed
            description: >-
              Get Current User's Recently Played Tracks: Get tracks from the
              current user’s recently played tracks. Note: Currently doesn’t
              support podcast episodes.
            path: /me/player/recently-played
            requestSchema: ./json-schemas/playerRecentlyPlayed.request.json
            responseSchema: ./json-schemas/playerRecentlyPlayed.response.json
          - type: Query
            field: search
            description: >-
              Search for an Item: Get Spotify Catalog information about albums,
              artists, playlists, tracks, shows or episodes that match a keyword
              string.
            path: /search
            requestSchema: ./json-schemas/search.request.json
            responseSchema: ./json-schemas/search.response.json
          - type: Query
            field: show
            description: >-
              Get a Show: Get Spotify catalog information for a single show
              identified by its unique Spotify ID.
            path: /shows/{args.id}
            requestSchema: ./json-schemas/show.request.json
            responseTypeName: ShowObject
          - type: Query
            field: showEpisodes
            description: >-
              Get a Show's Episodes: Get Spotify catalog information about an
              show’s episodes. Optional parameters can be used to limit the
              number of episodes returned.
            path: /shows/{args.id}/episodes
            requestSchema: ./json-schemas/showEpisodes.request.json
            responseSchema: ./json-schemas/showEpisodes.response.json
          - type: Query
            field: shows
            description: >-
              Get Multiple Shows: Get Spotify catalog information for several
              shows based on their Spotify IDs.
            path: /shows
            requestSchema: ./json-schemas/shows.request.json
            responseSchema: ./json-schemas/shows.response.json
          - type: Query
            field: track
            description: >-
              Get a Track: Get Spotify catalog information for a single track
              identified by its unique Spotify ID.
            path: /tracks/{args.id}
            requestSchema: ./json-schemas/track.request.json
            responseTypeName: TrackObject
          - type: Query
            field: trackAudioFeatures
            description: >-
              Get Audio Features for a Track: Get audio feature information for
              a single track identified by its unique Spotify ID.
            path: /audio-features/{args.id}
            requestSchema: ./json-schemas/trackAudioFeatures.request.json
            responseTypeName: AudioFeaturesObject
          - type: Query
            field: tracks
            description: >-
              Get Several Tracks: Get Spotify catalog information for multiple
              tracks based on their Spotify IDs.
            path: /tracks
            requestSchema: ./json-schemas/tracks.request.json
            responseSchema: ./json-schemas/tracks.response.json
          - type: Query
            field: tracksAudioFeatures
            description: >-
              Get Audio Features for Several Tracks: Get audio features for
              multiple tracks based on their Spotify IDs.
            path: /audio-features
            requestSchema: ./json-schemas/tracksAudioFeatures.request.json
            responseSchema: ./json-schemas/tracksAudioFeatures.response.json
